oak_dice_detector:
  ros__parameters:

    camera_frame: oak_rgb_camera_optical_frame

    homography_frame: "camera_frame_front"
    world_frame: "world"

    image_width: 1280
    image_height: 720
    fps: 15.0

    show_preview: true
    show_mask: true
    show_face_roi: true

    # Yellow segmentation
    h_min: 18
    s_min: 80
    v_min: 80

    h_max: 40
    s_max: 255
    v_max: 255

    # Dice detection
    min_dice_area: 300.0
    min_aspect_ratio: 0.55
    max_aspect_ratio: 1.60

    # Normalized face
    face_roi_size: 200
    face_inner_margin: 0.1

    # Pips
    pip_min_area_ratio: 0.002
    pip_max_area_ratio: 0.035
    pip_min_circularity: 0.45

    pip_min_radius_ratio: 0.025
    pip_max_radius_ratio: 0.13

    adaptive_block_size: 31
    adaptive_c: 6

    pip_close_kernel_size: 5
    pip_close_iterations: 1

    pip_open_kernel_size: 3
    pip_open_iterations: 1

    # Temporal filtering
    history_size: 7
    min_consistent_detections: 4

